### ISSUE TITLE
Won't Update, no "team.json" acknowledgement

### ISSUE THREAD

**Issue by EposVox** [guitaristtom/SSPokemonHUD#1]
Hi!
Your documentation ending at "and you should be good." leaves a lot to be desired. This currently isn't working for me.
There's a note in the py output saying "You will see lots of spam about team.json" but I do not. I renamed team.example.json to team.json and am editing it, but at no point - even after relaunching the script and clearing browser cache, does it ever change or update pokemon.
The console output never acknowledges the team.json file. 

What am I missing? Thanks!

**Comment by ThomasHineXYZ** [comment]
My apologies for not getting back to you sooner, I've been studying and doing midterm exams.

I see you closed this, were you able to get it to work?

It's been on my to-do list for a while to remake this from scratch, as it was my first real Python project. Another idea was making it as a plugin directly for OBS, which should run better than using a Python script as an abstract for it.

**Comment by EposVox** [comment]
all good. I did! For whatever reason the setup.py was not creating the team.json file at first, and the script wasn't updating from one I made, but eventually starting from scratch again got it working.
I'm actually working on a video involving this atm; I'd love to see/promote an OBS plugin for it (stretch goals to include badge indicators and etc. too!) if that happens! That was going to be something I mentioned at the end of the video wanting to see.

**Comment by ThomasHineXYZ** [comment]
I started working on the OBS plugin re-write of this. So far I just have the OBS plugin settings working right now, as I'm _trying_ to focus on midterms right now. But _at least_ it's something so far.

![Screenshot from 2020-10-23 18-49-18](https://user-images.githubusercontent.com/6890628/97123584-c4360e00-16e9-11eb-95cf-b403d3c72dbc.png)

Here's a link to that project's repo: https://github.com/guitaristtom/obspokemonhud

**Comment by EposVox** [comment]
Looking good so far! Awesome. I would like to request some flexibility with the background as most layouts with these parties use a separate layout, etc.
We modified the original project for that here: https://github.com/HunterAP23/SSPokemonHUD
Here's an image example https://cdn.discordapp.com/attachments/500841307242102786/768983633951981608/unknown.png
